### ISSUE TITLE
Error requesting review when using `create_pr`

### ISSUE THREAD

**Issue by Sassiest01** [SituDevelopment/automation#116] opened 2024-03-13 02:30 UTC
### Description

There is a gh: Invalid request. error that is stopping review from being requested from the Employees team on any PR.

### How To Reproduce

1. `create_pr integro_backend bug` 

### Expected Behavior

This should successfully request reviews from the Employees team when you create a PR.

### Additional Context

- Ran on the situ development server logged in as nathan

### Log Output

```shell
Requesting review from 'Employees' team...
gh: Invalid request.

No subschema in "anyOf" matched.
"reviewers" wasn't supplied.
"team_reviewers" wasn't supplied. (HTTP 422)
Error requesting review

Goodbye...
```

**Comment by willsawyerrrr** [comment] 2024-05-14 21:21
Cannot reproduce. Closing.

**Closed by willsawyerrrr** 2024-05-14 21:21 UTC
Labels: bug
